### PR TITLE
Update to support CommonMark >= 0.7.3 and clean up code

### LINKED ISSUE #24: CommonMark 0.6.0 breaks compatibility
Hi, it seems CommonMark (which was uploaded yesterday to pypi) breaks compatibility with this package. The error:

```
>>> from recommonmark.parser import CommonMarkParser
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/manuelmiranda/.virtualenvs/docs/lib/python2.7/site-packages/recommonmark/parser.py", line 9, in <module>
    from CommonMark import DocParser, HTMLRenderer
ImportError: cannot import name DocParser
```

Forcing the installation of 0.5.4 works again. Tested with both 0.2.0 and 0.1.1 versions.

### PR DESCRIPTION
**Pull request by agjohnson**
This was already dealing with a rewrite due to the spec change on CommonMark, so
I took the opportunity to modernize the code and clean things up as well.

* Updates to support CommonMark==0.7.3
* Reworks pattern for handling CommonMark nodes, mimic docutils visit/depart
  pattern
* Drops SectionHandler class, as it was only used in one place. Merge into the
  parser class, where it is used
* Drops requirements file for setup.py config. As this is a package, requirements.txt  is superfluous
* Adds a number of more detailed test cases
* Adds test runner for 3.5, 3.6
* Updates strictness on prospector, cleans up linting errors and docstring
  problems

Fixes #24

### CODE REVIEW

**Comment by ericholscher** [comment]
Looks good to me. Does this have any backwards incompat changes? I know there was some bits around changing the importable name of items from the previous release that was possibly causing breaking if we do a new release.

**Comment by agjohnson** [comment]
@ericholscher it may have, but because tests were lacking before, I can't be sure. I'd say it warrants bumping a major release version though.

**Comment by ericholscher** [comment]
+1 on bumping the version (or calling it 1.0) and getting it out the door.

**Comment by agjohnson** [comment]
I added in the pending xref feature, but had to make a number of bug fixes on it. The implementation didn't account for URLs like: 'example.html', or '/example'. My change instead wraps an `reference` node in a `pending_xref`. The pending xref replaces itself with the `reference` when the lookup fails.

Oops and tests broke

**Comment by agjohnson** [comment]
So this should be ready to go now. This deprecates the auto doc ref feature, replacing it with the built in linking, which i noted in the docs. The auto doc reference feature was throwing exceptions, and in the end, doing what `pending_xref` does anyways.

**Comment by ericholscher** [comment]
I'll give this a bigger review when I can. I'll also run it against some repos I have that use recommonmark, to make sure it works properly :+1:. The linking change is somewhat backwards incompat (in that it will link things magically when people don't have anything enabled), so we should probably rev the major?

**Comment by agjohnson** [comment]
Cool. Yup, either way this is a big backwards incompatible update. I'll run against some more repos myself as well, see if anything pops up from these changes.

**Comment by agjohnson** [comment]
@ericholscher know of any projects using recommonmark off the top of your head? @humitos might be able to help in QA here.

**Comment by ericholscher** [comment]
Hmm, not 100% -- we're using it in the writethedocs/www repo, and the recommonmark docs itself.

**Comment by agjohnson** [comment]
Noticed building the recommonmark docs that inline literals seem to not create correctly. I'll double check this.

**Comment by agjohnson** [comment]
Yup, inline code wasn't parsing. Added this and the test docs look better.

**Comment by mblaettler** [comment]
I've just stumbled upon this PR. It would make my PR #70 obsolete and the basic table support introduced in PR #68 will stop working.

What's your timeline regarding this PR? Do you plan to merge it and create a new version within the next days/weeks or is there still some work left?

FYI: I just tried to compile our documentation with this branch. Unfortunately, I ran into an error:
```
Exception occurred:
  File "/home/projects/CMS/recommonmark/recommonmark/parser.py", line 134, in visit_link
    else mdnode.parent.sourcepos[0][0])
TypeError: 'NoneType' object has no attribute '__getitem__'
The full traceback has been saved in /tmp/sphinx-err-duyc9p.log, if you want to report the issue to the developers.
```
It might be caused by our links, since we use the file extension within our links (e.g. `[some link](link.md)`).
We'd prefer to keep it that way, because these kind of links also work within the repo browser of GitHub.

**Comment by agjohnson** [comment]
All that is left here is testing. This will be the path forward for this module, we shouldn't continue pinning to the old versions of commonmark-py.

Looks like your test encountered a bug, but I don't think it has anything to do with the reference target. Instead, the expected `sourcepos` is empty, for whatever reason that is.

I lean towards getting this merged and maybe getting a beta release out. We really just need to test this and the new commonmark. I think this should be merged and tickets for bugs like the above opened against this, otherwise this will just rot.

@ericholscher sound okay?

**Comment by mblaettler** [comment]
Ok, so I'll close my two PRs in favor to this PR.

By the beginning of next week, I'll also do some further testing on this branch (if not already merged).

**Comment by ericholscher** [comment]
Yea, I'd like to get this merged if possible. It is just sitting around rotting, currently.

**Comment by agjohnson** [comment]
@mblaettler Could you open a new issue with a report of the bug you're hitting -- along with a test case if possible? I'll merge this into master so that we can at least be mostly current.

**Comment by mblaettler** [comment]
I'm out of office until Monday. I'll create an issue with test case by the beginning of next week.

**Comment by leniy** [comment]
I know `recommonmark` will never support `table` , cause this is a major further than `markdown` , to let people to use rst.

So,is there any other `Parser` for `sphinx` to use ?

**Comment by iliatimofeev** [comment]
`recommonmark` is a cool tool and I would like to use both `recommonmark` and `CommonMark` in one project.  `CommonMark` has been improved since `0.5.4` Is any forecast when this merge will be released?
